services:
  front:
    build:
      context: ./front
      target: development
    ports:
      - "9000:9000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0

  back:
    build:
      context: ./back
      target: development
    ports:
      - "3011:3011"
    volumes:
      - ./back:/app
      - /app/node_modules

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025" # Веб-интерфейс (тут вы будете читать письма)
      - "1025:1025" # SMTP порт (сюда NestJS будет отправлять письма)
    restart: unless-stopped
