import { EquipmentType, ItemRarity } from '../../generated/client';

export const SEEDED_CONSUMABLES = [
  {
    name: 'Lesser Experience Potion',
    description: 'Grants 100 experience when consumed.',
    price: 50,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Mild Experience Potion',
    description: 'Grants 500 experience when consumed.',
    price: 200,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Higher Experience Potion',
    description: 'Grants 2,000 experience when consumed.',
    price: 600,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Lesser Health Potion',
    description: 'Restores 50 health when consumed.',
    price: 25,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Mild Health Potion',
    description: 'Restores 150 health when consumed.',
    price: 75,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Higher Health Potion',
    description: 'Restores 500 health when consumed.',
    price: 200,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Lesser Attack Potion',
    description: 'Increases Damage by 5 for one battle.',
    price: 40,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Mild Attack Potion',
    description: 'Increases Damage by 15 for one battle.',
    price: 120,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Higher Attack Potion',
    description: 'Increases Damage by 50 for one battle.',
    price: 350,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Lesser Defense Potion',
    description: 'Increases Defense rating by 5 for one battle.',
    price: 40,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Mild Defense Potion',
    description: 'Increases Defense rating by 15 for one battle.',
    price: 120,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Higher Defense Potion',
    description: 'Increases Defense rating by 50 for one battle.',
    price: 350,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Free Attribute Potion',
    description: 'Grants 1 free attribute point when consumed.',
    price: 1000,
    rarity: ItemRarity.UNIQUE,
    equipmentType: EquipmentType.POTION,
  },
  {
    name: 'Scroll of Attack',
    description: 'Casts a spell that increases attack.',
    price: 250,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.SCROLL,
  },
  {
    name: 'Scroll of Defense',
    description: 'Casts a spell that increases defense.',
    price: 250,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.SCROLL,
  },
  {
    name: 'Town Portal Scroll',
    description: 'Opens a portal to the nearest town.',
    price: 100,
    rarity: ItemRarity.QUEST,
    equipmentType: EquipmentType.SCROLL,
  },
] as const;
