import { EquipmentType, ItemRarity } from '../../generated/client';

export const SEEDED_CONSUMABLES = [
  // Health potions restore persistent health during an active dungeon run.
  {
    name: 'Minor Health Potion',
    description: 'Restores up to 50 Health during a dungeon expedition.',
    price: 60,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
    level: 1,
  },
  {
    name: 'Lesser Health Potion',
    description: 'Restores up to 120 Health during a dungeon expedition.',
    price: 150,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
    level: 10,
  },
  {
    name: 'Medium Health Potion',
    description: 'Restores up to 250 Health during a dungeon expedition.',
    price: 360,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 20,
  },
  {
    name: 'Mild Health Potion',
    description: 'Restores up to 450 Health during a dungeon expedition.',
    price: 700,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 30,
  },
  {
    name: 'Greater Health Potion',
    description: 'Restores up to 700 Health during a dungeon expedition.',
    price: 1200,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 40,
  },
  {
    name: 'Higher Health Potion',
    description: 'Restores up to 1000 Health during a dungeon expedition.',
    price: 1800,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 50,
  },

  // Tier 1 (Level 10+)
  {
    name: 'Lesser Experience Potion',
    description: 'Increases experience gained by 10% for 4 hours.',
    price: 100,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
    level: 10,
  },
  {
    name: 'Lesser Attack Potion',
    description: 'Increases Damage by 5 for 4 hours.',
    price: 80,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
    level: 10,
  },
  {
    name: 'Lesser Defense Potion',
    description: 'Increases Defense rating by 5 for 4 hours.',
    price: 80,
    rarity: ItemRarity.COMMON,
    equipmentType: EquipmentType.POTION,
    level: 10,
  },

  // Tier 2 (Level 20+)
  {
    name: 'Medium Experience Potion',
    description: 'Increases experience gained by 20% for 4 hours.',
    price: 240,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 20,
  },
  {
    name: 'Medium Attack Potion',
    description: 'Increases Damage by 10 for 4 hours.',
    price: 180,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 20,
  },
  {
    name: 'Medium Defense Potion',
    description: 'Increases Defense rating by 10 for 4 hours.',
    price: 180,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 20,
  },

  // Tier 3 (Level 30+)
  {
    name: 'Mild Experience Potion',
    description: 'Increases experience gained by 30% for 4 hours.',
    price: 500,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 30,
  },
  {
    name: 'Mild Attack Potion',
    description: 'Increases Damage by 20 for 4 hours.',
    price: 360,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 30,
  },
  {
    name: 'Mild Defense Potion',
    description: 'Increases Defense rating by 20 for 4 hours.',
    price: 360,
    rarity: ItemRarity.MAGIC,
    equipmentType: EquipmentType.POTION,
    level: 30,
  },
  {
    name: 'Free Attribute Potion',
    description: 'Grants 1 free attribute point when consumed.',
    price: 2000,
    rarity: ItemRarity.UNIQUE,
    equipmentType: EquipmentType.POTION,
    level: 30,
  },

  // Tier 4 (Level 40+)
  {
    name: 'Greater Experience Potion',
    description: 'Increases experience gained by 40% for 4 hours.',
    price: 900,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 40,
  },
  {
    name: 'Greater Attack Potion',
    description: 'Increases Damage by 30 for 4 hours.',
    price: 600,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 40,
  },
  {
    name: 'Greater Defense Potion',
    description: 'Increases Defense rating by 30 for 4 hours.',
    price: 600,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 40,
  },

  // Tier 5 (Level 50+)
  {
    name: 'Higher Experience Potion',
    description: 'Increases experience gained by 50% for 4 hours.',
    price: 1600,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 50,
  },
  {
    name: 'Higher Attack Potion',
    description: 'Increases Damage by 50 for 4 hours.',
    price: 1000,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 50,
  },
  {
    name: 'Higher Defense Potion',
    description: 'Increases Defense rating by 50 for 4 hours.',
    price: 1000,
    rarity: ItemRarity.RARE,
    equipmentType: EquipmentType.POTION,
    level: 50,
  },
] as const;
