ALTER TABLE "Clan"
ADD COLUMN "treasureLevel" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "armoryLevel" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ClanMember"
ADD COLUMN "contributedGold" INTEGER NOT NULL DEFAULT 0;
