name: project-check
on: push
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: installation
        run: cd ./front && rm -f package-lock.json && npm i && cd ../back && npm i

      - name: lint-front
        run: cd ./front && npm run lint

      - name: lint-back
        run: cd ./back && npm run lint

      - name: test-back
        run: cd ./back && npm run test

      - name: test
        run: cd ./front && npm run test
