name: project-check
on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: installation
      run: npm ci

    - name: lint
      run: npx eslint .

    - name: test
      run: npm run test
